// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MainElm from "../elm/Main.elm";

var elm = MainElm.Elm;

function attemptFocus(id, n) {
  var el = document.getElementById(id);
  if (el == null) {
    if (n > 0) {
      setTimeout((function () {
              attemptFocus(id, n - 1 | 0);
            }), 16);
      return ;
    } else {
      return ;
    }
  } else {
    el.focus({
          preventScroll: true
        });
    if (n > 0) {
      setTimeout((function () {
              var cur = document.activeElement;
              if (cur == null) {
                return attemptFocus(id, n - 1 | 0);
              }
              var want = document.getElementById(id);
              if (!(want == null) && cur !== want) {
                return attemptFocus(id, n - 1 | 0);
              }
              
            }), 16);
      return ;
    } else {
      return ;
    }
  }
}

function deferFocus(id) {
  setTimeout((function () {
          attemptFocus(id, 12);
        }), 0);
}

function doBlur(id) {
  var el = document.getElementById(id);
  if (el == null) {
    var el$1 = document.activeElement;
    if (!(el$1 == null) && (id === "" || el$1.id === id)) {
      el$1.blur();
      return ;
    } else {
      return ;
    }
  }
  el.blur();
}

function doScroll(msg) {
  var el = document.getElementById("buffer-body");
  if (el == null) {
    return ;
  }
  if (msg.action === "center") {
    var mid = Math.max(0, (el.scrollHeight - el.clientHeight) / 2);
    el.scrollTo({
          top: mid,
          behavior: "auto"
        });
    return ;
  }
  var page = Math.max(120, Math.floor(el.clientHeight * 0.9));
  var delta = msg.dir >= 0 ? page : - page;
  el.scrollBy({
        top: delta,
        behavior: "auto"
      });
}

function paletteIsOpen() {
  var match = document.querySelector("#palette.open");
  return !(match == null);
}

function isShellEditable(el) {
  var tag = el.tagName.toLowerCase();
  var id = el.id;
  if (id === "palette-input") {
    return paletteIsOpen();
  } else if (tag === "input" || tag === "textarea") {
    return true;
  } else {
    return el.classList.contains("terminal-input");
  }
}

function shellKey(key, ctrl) {
  if (ctrl && (key === "f" || key === "F" || key === "b" || key === "B" || key === "[" || key === "c")) {
    return true;
  }
  switch (key) {
    case "/" :
    case ":" :
    case "?" :
    case "ArrowDown" :
    case "ArrowRight" :
    case "ArrowUp" :
    case "Enter" :
    case "Escape" :
    case "G" :
    case "Tab" :
    case "g" :
    case "j" :
    case "k" :
    case "l" :
    case "z" :
        return true;
    default:
      return false;
  }
}

function shouldPrevent(ev) {
  var key = ev.key;
  var ctrl = ev.ctrlKey;
  var meta = ev.metaKey;
  if (meta) {
    return false;
  }
  var el = document.activeElement;
  if (el == null) {
    return shellKey(key, ctrl);
  } else if (el.id === "palette-input" && !paletteIsOpen()) {
    el.blur();
    return shellKey(key, ctrl);
  } else if (isShellEditable(el)) {
    if (key === "Escape" || ctrl && (key === "[" || key === "c")) {
      return true;
    } else if (el.id === "palette-input" && paletteIsOpen()) {
      if (key === "Enter" || key === "Tab" || key === "ArrowDown" || key === "ArrowUp" || key === "j") {
        return true;
      } else {
        return key === "k";
      }
    } else {
      return false;
    }
  } else {
    return shellKey(key, ctrl);
  }
}

function boot() {
  var node = document.getElementById("app");
  if (node == null) {
    console.error("missing #app");
    return ;
  }
  var isMobile = window.matchMedia("(max-width: 860px)").matches;
  var app = elm.Main.init({
        node: node,
        flags: {
          isMobile: isMobile
        }
      });
  app.ports.focus.subscribe(function (id) {
        deferFocus(id);
      });
  app.ports.blur.subscribe(function (id) {
        doBlur(id);
      });
  app.ports.scrollBuffer.subscribe(function (msg) {
        doScroll(msg);
      });
  document.addEventListener("keydown", (function (ev) {
          if (shouldPrevent(ev)) {
            ev.preventDefault();
            return ;
          }
          
        }), true);
}

boot();

export {
  elm ,
  attemptFocus ,
  deferFocus ,
  doBlur ,
  doScroll ,
  paletteIsOpen ,
  isShellEditable ,
  shellKey ,
  shouldPrevent ,
  boot ,
}
/* elm Not a pure module */
